---
substitutions:
  name: climate_downstairs
  friendly_name: Luftvärmepump

esphome:
  name: ${name}

esp8266:
  board: d1_mini

# https://esphome.io/components/wifi.html
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  ap:
    ssid: "$friendly_name Hotspot"
    password: !secret wifi_fallback_ssid_password

logger:
api:
ota:
  password: !secret ota_password
captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ${friendly_name} ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP
    ssid:
      name: ${friendly_name} SSID
    bssid:
      name: ${friendly_name} BSSID

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: ${friendly_name} Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    update_interval: 60s

  # Useexternal temp sensor.
  - platform: homeassistant
    name: "Temperature Sensor From Home Assistant"
    entity_id: sensor.temperature_downstairs_temperature
    id: esp_downstairs_temperature
    on_value:
      then:
        - lambda: |-
            if(id(esp_downstairs_temperature).has_state()) {
              id(${name}).set_remote_temperature(x);
            } else {
              // use internal temp
              id(${name}).set_remote_temperature(0);
              ESP_LOGW("temperature", "using internal temp");
            }
    filters:
      - heartbeat: 20s

external_components:
  - source: github://geoffdavis/esphome-mitsubishiheatpump

climate:
  - platform: mitsubishi_heatpump
    name: ${friendly_name}
    id: ${name}
    hardware_uart: UART0
    #baud_rate: 9600
    supports:
      mode: ["HEAT_COOL", "COOL", "HEAT", "DRY", "FAN_ONLY", "OFF"]
      fan_mode:
        ["ON", "OFF", "AUTO", "LOW", "MEDIUM", "HIGH", "MIDDLE", "FOCUS"]
      swing_mode: ["OFF", "VERTICAL", "HORIZONTAL", "BOTH"]
    visual:
      min_temperature: 10
      max_temperature: 31
      temperature_step: 0.5
