---
substitutions:
  name: weather-station

esphome:
  name: $name

# https://esphome.io/components/wifi.html
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.71.79
    gateway: 192.168.71.1
    subnet: 255.255.255.0

  ap:
    ssid: "$name Hotspot"
    password: !secret wifi_fallback_ssid_password

esp8266:
  board: d1_mini

logger:
api:
ota:
  password: !secret ota_password
captive_portal:

i2c:
  sda: D2
  scl: D1
  scan: True

spi:
  clk_pin: D5
  miso_pin: D6
  mosi_pin: D7

as3935_spi:
  cs_pin: D8
  irq_pin: D3
  indoor: false
  noise_level: 2
  spike_rejection: 4 # Default 2
  lightning_threshold: 1
  mask_disturber: false
  div_ratio: 0
  capacitance: 5
  watchdog_threshold: 2

# Example configuration entry
sensor:
  - platform: dht
    pin: D4
    model: AM2302
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s

  - platform: bh1750
    name: "Illuminance"
    address: 0x23
    update_interval: 60s

  - platform: as3935
    lightning_energy:
      name: "Lightning Energy"
    distance:
      name: "Distance Storm"

binary_sensor:
  - platform: as3935
    name: "Storm Alert"
